project_id = "tcmhvrlsaggyuukdscue"

[functions.admin-delete-image]
verify_jwt = false

[functions.admin-update-profile]
verify_jwt = false

[functions.admin-manage-like]
verify_jwt = false

[functions.admin-upload-image]
verify_jwt = false

[functions.admin-list-profiles]
verify_jwt = false

[functions.admin-list-support]
verify_jwt = false

[functions.admin-get-profile-likes]
verify_jwt = false

[functions.create-unlock-payment]
verify_jwt = true

[functions.detect-language]
verify_jwt = false

[functions.purchase-credits]
verify_jwt = true

[functions.reset-daily-credits]
verify_jwt = false

[functions.search-giphy]
verify_jwt = true

[functions.seed-profiles]
verify_jwt = false

[functions.send-support-email]
verify_jwt = true

[functions.subscribe-premium]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.verify-subscription]
verify_jwt = true
