// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // MODIFICA MANUALE: lock "no-op". Il lock predefinito (Web Locks API) poteva
    // bloccarsi e lasciare query/sessione in attesa per minuti durante la
    // navigazione tra le pagine. Eseguendo l'operazione direttamente il
    // problema sparisce.
    lock: (_name: string, _acquireTimeout: number, fn: () => Promise<unknown>) => fn(),
  }
});